version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: otto
    binary: otto
    main: ./cmd/otto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/open-telemetry/sig-project-infra/otto/internal.Version={{.Version}}

dockers:
  - image_templates:
      - "ghcr.io/open-telemetry/sig-project-infra/otto:{{ .Version }}"
      - "ghcr.io/open-telemetry/sig-project-infra/otto:latest"
    dockerfile: Dockerfile.goreleaser
    ids:
      - otto
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=Otto"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/open-telemetry/sig-project-infra"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
    use: docker

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Use formats instead of format (deprecated)
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        # Use formats instead of format (deprecated)
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - config.example.yaml

checksum:
  name_template: "checksums.txt"

# Use version_template instead of name_template for snapshot (deprecated)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"