name: Otto Release

# PR-based release trigger only
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'otto/**'

permissions:
  contents: write
  packages: write

jobs:
  # PR-based tag creation (only runs on merged PRs with release label)
  create-release:
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}
      release_created: ${{ steps.create_tag.outputs.release_created }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine release type
        id: release_type
        run: |
          RELEASE_TYPE="patch"
          
          if contains(github.event.pull_request.labels.*.name, 'release:major'); then
            RELEASE_TYPE="major"
          elif contains(github.event.pull_request.labels.*.name, 'release:minor'); then
            RELEASE_TYPE="minor"
          fi
          
          echo "release_type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
      
      - name: Calculate next version with svu
        id: svu
        uses: charlesthomas/github-action-svu@v1.0.2
        with:
          type: ${{ steps.release_type.outputs.release_type }}
          working-directory: otto
          # Ensure prefix is set correctly
          prefix: "v"
          # Handle case when no previous tags exist
          fallback: "0.1.0"
          # Use the same configuration as in .svu.yml
          metadata: false
          pre: false
      
      - name: Create tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: v${{ steps.svu.outputs.version }}
        run: |
          # Extract PR title and body for release notes
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create and push tag
          echo "Creating tag $NEW_VERSION"
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION from PR #$PR_NUMBER: $PR_TITLE"
          git push origin "$NEW_VERSION"
          
          echo "tag_name=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "release_created=true" >> $GITHUB_OUTPUT

  # Main release job - runs after tag creation
  goreleaser:
    needs: [create-release]
    if: needs.create-release.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./otto
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the newly created tag
          ref: ${{ needs.create-release.outputs.tag_name }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./otto/go.mod
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Install cosign for artifact signing
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0
        with:
          cosign-release: 'v2.2.2'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ./otto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # These secrets need to be set in the repository settings
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}