name: Otto Tests

on:
  push:
    branches: [main]
    paths:
      - "otto/**"
  pull_request:
    branches: [main]
    paths:
      - "otto/**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./otto

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: true
          cache-dependency-path: otto/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./otto

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Run linter
        uses: golangci/golangci-lint-action@latest
        with:
          version: latest
          working-directory: otto
